In [1]:
import numpy as np
import time

# Vector Creation

In [4]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.65228013 0.38999445 0.70382224 0.35566351], a shape = (4,), a data type = float64


In [9]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.07929309 0.56346063 0.96270414 0.83315483], a shape = (4,), a data type = float64


**manual enteries**

In [11]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2])
print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2])
print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int32
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


# Operations on Vectors

In [12]:
a= np.arange(10)

In [13]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
#access an element
print(a[1])

1


In [18]:
# access the last element, negative indexes count from the end
print(a[-1])

9


In [19]:
#indexs must be within the range of the vector or they will produce and error
try: 
    t = a[10]
except Exception as e:
    print("Not in range")
    print(e)

Not in range
index 10 is out of bounds for axis 0 with size 10


**slicing**

In [20]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
#access 5 consecutive elements (start:stop:step)
c = a[2:7:1]
print(c)

[2 3 4 5 6]


In [22]:
# access 3 elements separated by two 
c = a[2:7:2]
print("a[2:7:2] = ", c)

a[2:7:2] =  [2 4 6]


In [23]:
# access all elements index 3 and above
c = a[3:]
print("a[3:]    = ", c)

a[3:]    =  [3 4 5 6 7 8 9]


In [24]:
# access all elements below index 3
c = a[:3]
print("a[:3]    = ", c)

a[:3]    =  [0 1 2]


In [27]:
# access all elements
c = a[:]     
print("a[:]     = ", c)

a[:]     =  [0 1 2 3 4 5 6 7 8 9]


**single vector operations**

In [28]:
a = np.array([1,2,3,4])
print(f"a             : {a}")

a             : [1 2 3 4]


In [29]:
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

b = -a        : [-1 -2 -3 -4]


In [30]:
# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")


b = np.sum(a) : 10


In [31]:
b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = np.mean(a): 2.5


In [32]:
b = a**2
print(f"b = a**2      : {b}")

b = a**2      : [ 1  4  9 16]


**Vector Element-wise operations**

In [33]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [34]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


**Scalar Vector Operations**

In [35]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


**Vectors Dot Product**

we can implement our own dot product function using for loop

In [36]:
def my_dot(a, b):
    x = 0
    for i in range(len(a)):
        x = x + a[i] * b[i]
    return x

In [38]:
#testing
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(my_dot(a,b))

24


we can use predefined numpy dot product function too

In [40]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a,b)
print(c)

24


**vector vs for loop**

In [42]:
np.random.seed(1)
# very large arrays
a = np.random.rand(10000000)
b = np.random.rand(10000000)
tic = time.time()  # capture start time
#using the numpy function for dot product
c = np.dot(a,b)
toc = time.time() ## capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

np.dot(a, b) =  2501072.5817
Vectorized version duration: 244.7593 ms 


In [46]:
tic = time.time()  # capture start time
#using our defined version of dot product
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

my_dot(a, b) =  2501072.5817
loop version duration: 6695.5402 ms 


In [47]:
del(a);del(b)  #remove these big arrays from memory

In [49]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


# Matrices

**Creating Matrices**

In [53]:
a = np.zeros((1,5))
print(f"shape of a is : {a.shape}")
print(f"a: {a}")


a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}")
print(f"a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

shape of a is : (1, 5)
a: [[0. 0. 0. 0. 0.]]
a shape = (2, 1)
a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.04997798]]


In [63]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5, 4], [4, 2], [3,3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5,4],   # One can also
              [4,2],   # separate values
              [3,3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 2), np.array: a = [[5 4]
 [4 2]
 [3 3]]
 a shape = (3, 2), np.array: a = [[5 4]
 [4 2]
 [3 3]]


**Operations on Matrices**

In [66]:
#vector indexing operations on matrices
                        #means we want two rows and rest fit all values in columns
a = np.arange(6).reshape(2, -1)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

a.shape: (2, 3), 
a= [[0 1 2]
 [3 4 5]]


In [72]:
#We can do the same with
a = np.arange(6).reshape(2, 3)
print(f"a.shape: {a.shape}, \na= {a}")

a.shape: (2, 3), 
a= [[0 1 2]
 [3 4 5]]


In [68]:
#similarly
                        #means we want two columns and rest fit all values in rows
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]


In [71]:
#We can do the same with
a = np.arange(6).reshape(3, 2)
print(f"a.shape: {a.shape}, \na= {a}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]


In [69]:
#indexing
    #second row and ist columns
print(a[1,0])

2


**Slicing**

In [80]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")


#access 5 consecutive elements (start:stop:step)
                #row 1 and do this 
print(f"Numbers are: a[0, 2:7:1]")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")



a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
Numbers are: a[0, 2:7:1]
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array


In [79]:


# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
